language: node_js
addons:
  firefox: "43.0"
node_js:
- '4.1'
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- npm install
- grunt serve &
- webdriver-manager update
- webdriver-manager start &
- sleep 3
script:
- ./node_modules/karma/bin/karma start test/karma.conf.js --single-run --browser=firefox
- ./node_modules/.bin/protractor ./test/protractor.conf.js --browser=firefox
