language: node_js
addons:
  firefox: "43.0"
node_js:
- '4.1'
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- npm install
- npm start &
- webdriver-manager update
- webdriver-manager start &
- sleep 3
script:
- npm run test
